image: elixir:1.7.2
services:
  - postgres:latest

variables:
  POSTGRES_DB: ranking_poller_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  MIX_ENV: test

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix ecto.create
  - make migrate

ex_tests:
  script:
    - make coverage
    - make style
  after_script:
    - make docs-report
