image: elixir:1.7.2

variables:
  POSTGRES_DB: ranking_poller_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  MIX_ENV: test

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

test-job:
  stage: test
  services:
    - postgres:latest
  before_script:
    - apt-get update && apt-get -y install postgresql-client
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
    - mix ecto.create
    - make migrate
  script:
    - mix inch --pedantic
    - mix credo --strict
    - mix coveralls -u

check-types-job:
  before_script:
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only dev
  variables:
    CI: "true"
    MIX_ENV: dev
  stage: test
  script:
    - mix compile
    - mix dialyzer
  cache:
    key: one-key-to-rull-them-all
    paths:
      - .cache/
