image: trenpixster/elixir:latest
services:
  - postgres:latest

variables:
  POSTGRES_DB: ranking_poller_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  MIX_ENV: test

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix deps.get --only test
  - mix deps.get --only docs
  - mix ecto.create
  - make migrate

mix:
  script:
    - make test
