language: elixir
elixir:
  - 1.6
otp_release:
  - 21.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis -u
  - make style
after_script:
  - MIX_ENV=docs mix inch.report
